theme: jekyll-theme-leap-day
title: Baxley Computer Care
description: Computer Services in Northeast Florida
show_downloads: false
google_analytics: UA-156560561-1
github:
  owner_name: Christopher Baxley
